### ISSUE TITLE
Build isn't possible

### ISSUE THREAD

**Issue by siainbuletin** [jeetsukumaran/obsidian-bibliosidian#2]
Hi, I'm trying to build your plugin from source following your instructions, but I'm getting an error that says the build script doesn't exist.
![Screenshot 2024-03-31 at 19 00 01](https://github.com/jeetsukumaran/obsidian-bibliosidian/assets/97026492/2fe153f8-abbc-4e96-b736-eeaf3be7f7e0)

this is the debug log:

0 verbose cli /usr/local/Cellar/node/21.7.1/bin/node /usr/local/bin/npm
1 info using npm@10.5.0
2 info using node@v21.7.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 0ms
9 timing config:load:project Completed in 4ms
10 timing config:load:file:/Users/siainbuletin/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:setEnvs Completed in 1ms
15 timing config:load Completed in 13ms
16 timing npm:load:configload Completed in 13ms
17 timing config:load:flatten Completed in 2ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 1ms
20 verbose title npm run build
21 verbose argv "run" "build"
22 timing npm:load:setTitle Completed in 4ms
23 timing npm:load:display Completed in 2ms
24 verbose logfile logs-max:10 dir:/Users/siainbuletin/.npm/_logs/2024-03-31T15_59_28_841Z-
25 verbose logfile /Users/siainbuletin/.npm/_logs/2024-03-31T15_59_28_841Z-debug-0.log
26 timing npm:load:logFile Completed in 9ms
27 timing npm:load:timers Completed in 0ms
28 timing npm:load:configScope Completed in 0ms
29 timing npm:load Completed in 47ms
30 silly logfile start cleaning logs, removing 1 files
31 timing command:run Completed in 11ms
32 verbose stack Error: Missing script: "build"
32 verbose stack
32 verbose stack To see a list of scripts, run:
32 verbose stack   npm run
32 verbose stack     at RunScript.run (/usr/local/lib/node_modules/npm/lib/commands/run-script.js:94:13)
32 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli-entry.js:61:5)
33 verbose cwd /Users/siainbuletin/local/brain-re/.obsidian/plugins
34 verbose Darwin 23.4.0
35 verbose node v21.7.1
36 verbose npm  v10.5.0
37 error Missing script: "build"
37 error
37 error To see a list of scripts, run:
37 error   npm run
38 verbose exit 1
39 timing npm Completed in 88ms
40 verbose code 1
41 error A complete log of this run can be found in: /Users/siainbuletin/.npm/_logs/2024-03-31T15_59_28_841Z-debug-0.log

**Comment by jeetsukumaran** [comment]
Did you run 

```
$ npm i
```

in the project directory first?

**Comment by siainbuletin** [comment]
I did. 

I did get an error or two (I'm sorry for the lack of specificity, I am currently away from a PC) from npm about a security vulnerability, but I ignored it. The first time I tried installing the program I actually used an npm update command that was recommended in the CLI to deal with the security vulnerabilities, but then `npm run build` wouldn't load anything at all after that, so I figured just breezing through the instructions without intervention would help.

**Comment by jeetsukumaran** [comment]
Ah, that explains it. 

The issue is with the dataview dependency:

https://github.com/blacksmithgu/obsidian-dataview/issues/2288

I don't actually use svelte or the calendar, but I do use Dataview. I've tried running the same fix, and get the same results.

Running the "fix", as you found out, breaks the build. I'm not familiar 

NOT running the fix  (i.e., just "npm run build" and ignoring the warning) "works" in the sense of building fine and the plugin running fine and the computer not melting on anything. I'm hoping this will be resolve on the dataview side.
