### ISSUE TITLE
I want to test this project but is there an easy way to install?

### ISSUE THREAD

**Issue by ulahcherubim** [jeetsukumaran/obsidian-bibliosidian#3]
Hi, I am interested in your project and it looks promising. But I don't know how to build a program from the packages and afraid of screwing up in the process. Is there another way to install your plugin or is the method mentioned in the readme is the only way?

**Comment by jeetsukumaran** [comment]
Yes, in the short term, I could set up a project release. This would involve you downloading a release archive and unpacking it into a subdirectory of your "``.obsidian/plugins/obsidian-bibliosidian``". Still not as easy as you might like, but at least there is no building of programs.

In the longer term, my plan is to make this community plugin, but I need to clean up the code for that. 

If you do not mind the first (i.e. downloading and copying files), then please open an issue for it so I'll remember it when I get some development time in here?

**Comment by ulahcherubim** [comment]
I tried using BRAT but it said main.js is missing. Can you build a release so that I can test this?

**Comment by jeetsukumaran** [comment]
Done on main branch (which is now the default branch 8686bd1a: https://github.com/jeetsukumaran/obsidian-bibliosidian/releases/tag/0.0.2
